import { Tajawal } from "next/font/google";
import "./globals.css";
import Footer from "@/components/ui/Footer";
import "@/lib/fontawesome"; // Import FontAwesome configuration

const tajawal = Tajawal({
  variable: "--font-tajawal",
  subsets: ["arabic", "latin"],
  weight: ["200", "300", "400", "500", "700", "800", "900"],
  display: "swap"
});

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html  >
      <body
        className={`${tajawal.variable} antialiased`}
      >
        {children}
          <Footer />
      </body>
    </html>
  );
}
